// Generated by CoffeeScript 1.10.0
(function() {
  var completed, prog, running, start, stop, total;

  running = null;

  completed = false;

  total = 1000;

  prog = progressDisplay('.progress-container', total);

  start = function() {
    running = true;
    $('.stop').removeClass('disabled');
    $('.start').addClass('disabled');
    return co(function*() {
      var i, j, mesg, ref;
      for (i = j = 1, ref = total; 1 <= ref ? j <= ref : j >= ref; i = 1 <= ref ? ++j : --j) {
        if (running) {
          prog.setValue(i);
          pinfo("Track " + i);
          (yield sleep(0.005));
        } else {
          return;
        }
      }
      completed = true;
      mesg = 'Generated NML file containing 1000 tracks';
      psuccess(mesg);
      (yield playSound('success'));
      (yield speak(mesg));
      return stop();
    });
  };

  stop = function(manual) {
    running = false;
    return co(function*() {
      if (manual) {
        pinfo('Stopping...');
        (yield sleep(1));
        pinfo('Stopped!');
      }
      $('.stop').addClass('disabled');
      $('.start').removeClass('disabled');
      if (completed) {
        return $('.next').removeClass('disabled');
      }
    });
  };

  $('.start').on('click', function() {
    if (!running) {
      return start();
    }
  });

  $('.stop').on('click', function() {
    if (running) {
      return stop(true);
    }
  });

  start();

}).call(this);
