// Generated by CoffeeScript 1.10.0
(function() {
  var running;

  running = true;

  $('button.stop').on('click', function() {
    running = false;
    return co(function*() {
      plog('Stopping...');
      (yield sleep(1));
      return plog('Stopped!');
    });
  });

  co(function*() {
    var i, j, mesg;
    for (i = j = 1; j <= 30; i = ++j) {
      if (running) {
        plog("Artist " + i);
        (yield sleep(0.3));
      } else {
        return;
      }
    }
    mesg = 'Found 30 new artists!';
    plog(mesg);
    return speak(mesg);
  });

}).call(this);
