// Generated by CoffeeScript 1.10.0
(function() {
  co(function*() {
    var i, j, results;
    results = [];
    for (i = j = 1; j <= 30; i = ++j) {
      plog("Artist " + i);
      results.push((yield sleep(0.5)));
    }
    return results;
  });

}).call(this);
