// Generated by CoffeeScript 1.10.0
(function() {
  window.sleep = function(delay) {
    return new Promise(function(resolve, reject) {
      return window.setTimeout(resolve, delay * 1000);
    });
  };

  window.speak = function(text) {
    if (window.speechSynthesis === void 0) {
      return;
    }
    return new Promise(function(resolve, reject) {
      var utterance;
      utterance = new SpeechSynthesisUtterance(text);
      window.speechSynthesis.speak(utterance);
      return utterance.onend = resolve;
    });
  };

  window.plog = function(text) {
    var output, p;
    output = $('.console');
    p = $('<p>').text(text).appendTo(output);
    return output.scrollTop(p.offset().top - output.offset().top + output.scrollTop());
  };

}).call(this);
