// Generated by CoffeeScript 1.10.0
(function() {
  window.sleep = function(delay) {
    return new Promise(function(resolve, reject) {
      return window.setTimeout(resolve, delay * 1000);
    });
  };

  window.plog = function(text) {
    var output, p;
    output = $('.console');
    p = $('<p>').text(text).appendTo(output);
    return output.scrollTop(p.offset().top - output.offset().top + output.scrollTop());
  };

}).call(this);
