// Generated by CoffeeScript 1.10.0
(function() {
  $(document).ready(function() {
    return window.setTimeout(function() {
      return $('#corner-note').fadeIn(1000);
    }, 1000);
  });

}).call(this);
