// Generated by CoffeeScript 1.10.0
(function() {
  var start, stop;

  start = function() {
    $('.stop').removeClass('disabled');
    $('.start').addClass('disabled');
    return co(function*() {
      var albumMsg, i, j, k, l, mesg;
      for (i = k = 1; k <= 3; i = ++k) {
        albumMsg = "Album " + i;
        phigh(albumMsg);
        for (j = l = 1; l <= 10; j = ++l) {
          pinfo("Track " + j);
          (yield sleep(0.2));
        }
      }
      mesg = 'Successfully imported 30 tracks';
      phigh(mesg);
      (yield playSound('success'));
      (yield speak(mesg));
      return stop();
    });
  };

  stop = function(manual) {
    $('.stop').addClass('disabled');
    $('.start').removeClass('disabled');
    return $('.next').removeClass('disabled');
  };

  start();

}).call(this);
